# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _wcs
else:
    import _wcs

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


def wcsinit(hstring:str) -> 'WCSPRM':
    return _wcs.wcsinit(hstring)

def wcs2pix(wcs:'WCSPRM', xpos:float, ypos:float) -> tuple[float,float]:
    return _wcs.wcs2pix(wcs, xpos, ypos)

def pix2wcs(wcs:'WCSPRM', xpix:float, ypix:float):
    return _wcs.pix2wcs(wcs, xpix, ypix)

class WCSPRM(object):
    r"""Proxy of C WorldCoor struct."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    xref = property(_wcs.WorldCoor_xref_get, _wcs.WorldCoor_xref_set, doc=r"""xref : double""")
    yref = property(_wcs.WorldCoor_yref_get, _wcs.WorldCoor_yref_set, doc=r"""yref : double""")
    xrefpix = property(_wcs.WorldCoor_xrefpix_get, _wcs.WorldCoor_xrefpix_set, doc=r"""xrefpix : double""")
    yrefpix = property(_wcs.WorldCoor_yrefpix_get, _wcs.WorldCoor_yrefpix_set, doc=r"""yrefpix : double""")
    xinc = property(_wcs.WorldCoor_xinc_get, _wcs.WorldCoor_xinc_set, doc=r"""xinc : double""")
    yinc = property(_wcs.WorldCoor_yinc_get, _wcs.WorldCoor_yinc_set, doc=r"""yinc : double""")
    rot = property(_wcs.WorldCoor_rot_get, _wcs.WorldCoor_rot_set, doc=r"""rot : double""")
    cd = property(_wcs.WorldCoor_cd_get, _wcs.WorldCoor_cd_set, doc=r"""cd : a(4).double""")
    dc = property(_wcs.WorldCoor_dc_get, _wcs.WorldCoor_dc_set, doc=r"""dc : a(4).double""")
    equinox = property(_wcs.WorldCoor_equinox_get, _wcs.WorldCoor_equinox_set, doc=r"""equinox : double""")
    epoch = property(_wcs.WorldCoor_epoch_get, _wcs.WorldCoor_epoch_set, doc=r"""epoch : double""")
    nxpix = property(_wcs.WorldCoor_nxpix_get, _wcs.WorldCoor_nxpix_set, doc=r"""nxpix : double""")
    nypix = property(_wcs.WorldCoor_nypix_get, _wcs.WorldCoor_nypix_set, doc=r"""nypix : double""")
    plate_ra = property(_wcs.WorldCoor_plate_ra_get, _wcs.WorldCoor_plate_ra_set, doc=r"""plate_ra : double""")
    plate_dec = property(_wcs.WorldCoor_plate_dec_get, _wcs.WorldCoor_plate_dec_set, doc=r"""plate_dec : double""")
    plate_scale = property(_wcs.WorldCoor_plate_scale_get, _wcs.WorldCoor_plate_scale_set, doc=r"""plate_scale : double""")
    x_pixel_offset = property(_wcs.WorldCoor_x_pixel_offset_get, _wcs.WorldCoor_x_pixel_offset_set, doc=r"""x_pixel_offset : double""")
    y_pixel_offset = property(_wcs.WorldCoor_y_pixel_offset_get, _wcs.WorldCoor_y_pixel_offset_set, doc=r"""y_pixel_offset : double""")
    x_pixel_size = property(_wcs.WorldCoor_x_pixel_size_get, _wcs.WorldCoor_x_pixel_size_set, doc=r"""x_pixel_size : double""")
    y_pixel_size = property(_wcs.WorldCoor_y_pixel_size_get, _wcs.WorldCoor_y_pixel_size_set, doc=r"""y_pixel_size : double""")
    ppo_coeff = property(_wcs.WorldCoor_ppo_coeff_get, _wcs.WorldCoor_ppo_coeff_set, doc=r"""ppo_coeff : a(6).double""")
    x_coeff = property(_wcs.WorldCoor_x_coeff_get, _wcs.WorldCoor_x_coeff_set, doc=r"""x_coeff : a(20).double""")
    y_coeff = property(_wcs.WorldCoor_y_coeff_get, _wcs.WorldCoor_y_coeff_set, doc=r"""y_coeff : a(20).double""")
    xpix = property(_wcs.WorldCoor_xpix_get, _wcs.WorldCoor_xpix_set, doc=r"""xpix : double""")
    ypix = property(_wcs.WorldCoor_ypix_get, _wcs.WorldCoor_ypix_set, doc=r"""ypix : double""")
    zpix = property(_wcs.WorldCoor_zpix_get, _wcs.WorldCoor_zpix_set, doc=r"""zpix : double""")
    xpos = property(_wcs.WorldCoor_xpos_get, _wcs.WorldCoor_xpos_set, doc=r"""xpos : double""")
    ypos = property(_wcs.WorldCoor_ypos_get, _wcs.WorldCoor_ypos_set, doc=r"""ypos : double""")
    crpix = property(_wcs.WorldCoor_crpix_get, _wcs.WorldCoor_crpix_set, doc=r"""crpix : a(9).double""")
    crval = property(_wcs.WorldCoor_crval_get, _wcs.WorldCoor_crval_set, doc=r"""crval : a(9).double""")
    cdelt = property(_wcs.WorldCoor_cdelt_get, _wcs.WorldCoor_cdelt_set, doc=r"""cdelt : a(9).double""")
    pc = property(_wcs.WorldCoor_pc_get, _wcs.WorldCoor_pc_set, doc=r"""pc : a(81).double""")
    projp = property(_wcs.WorldCoor_projp_get, _wcs.WorldCoor_projp_set, doc=r"""projp : a(10).double""")
    pvfail = property(_wcs.WorldCoor_pvfail_get, _wcs.WorldCoor_pvfail_set, doc=r"""pvfail : int""")
    projppv = property(_wcs.WorldCoor_projppv_get, _wcs.WorldCoor_projppv_set, doc=r"""projppv : a(2*MAXPV).double""")
    inv_x = property(_wcs.WorldCoor_inv_x_get, _wcs.WorldCoor_inv_x_set, doc=r"""inv_x : p.struct poly""")
    inv_y = property(_wcs.WorldCoor_inv_y_get, _wcs.WorldCoor_inv_y_set, doc=r"""inv_y : p.struct poly""")
    longpole = property(_wcs.WorldCoor_longpole_get, _wcs.WorldCoor_longpole_set, doc=r"""longpole : double""")
    latpole = property(_wcs.WorldCoor_latpole_get, _wcs.WorldCoor_latpole_set, doc=r"""latpole : double""")
    rodeg = property(_wcs.WorldCoor_rodeg_get, _wcs.WorldCoor_rodeg_set, doc=r"""rodeg : double""")
    imrot = property(_wcs.WorldCoor_imrot_get, _wcs.WorldCoor_imrot_set, doc=r"""imrot : double""")
    pa_north = property(_wcs.WorldCoor_pa_north_get, _wcs.WorldCoor_pa_north_set, doc=r"""pa_north : double""")
    pa_east = property(_wcs.WorldCoor_pa_east_get, _wcs.WorldCoor_pa_east_set, doc=r"""pa_east : double""")
    radvel = property(_wcs.WorldCoor_radvel_get, _wcs.WorldCoor_radvel_set, doc=r"""radvel : double""")
    zvel = property(_wcs.WorldCoor_zvel_get, _wcs.WorldCoor_zvel_set, doc=r"""zvel : double""")
    zpzd = property(_wcs.WorldCoor_zpzd_get, _wcs.WorldCoor_zpzd_set, doc=r"""zpzd : double""")
    zpr = property(_wcs.WorldCoor_zpr_get, _wcs.WorldCoor_zpr_set, doc=r"""zpr : double""")
    imflip = property(_wcs.WorldCoor_imflip_get, _wcs.WorldCoor_imflip_set, doc=r"""imflip : int""")
    prjcode = property(_wcs.WorldCoor_prjcode_get, _wcs.WorldCoor_prjcode_set, doc=r"""prjcode : int""")
    latbase = property(_wcs.WorldCoor_latbase_get, _wcs.WorldCoor_latbase_set, doc=r"""latbase : int""")
    ncoeff1 = property(_wcs.WorldCoor_ncoeff1_get, _wcs.WorldCoor_ncoeff1_set, doc=r"""ncoeff1 : int""")
    ncoeff2 = property(_wcs.WorldCoor_ncoeff2_get, _wcs.WorldCoor_ncoeff2_set, doc=r"""ncoeff2 : int""")
    zpnp = property(_wcs.WorldCoor_zpnp_get, _wcs.WorldCoor_zpnp_set, doc=r"""zpnp : int""")
    changesys = property(_wcs.WorldCoor_changesys_get, _wcs.WorldCoor_changesys_set, doc=r"""changesys : int""")
    printsys = property(_wcs.WorldCoor_printsys_get, _wcs.WorldCoor_printsys_set, doc=r"""printsys : int""")
    ndec = property(_wcs.WorldCoor_ndec_get, _wcs.WorldCoor_ndec_set, doc=r"""ndec : int""")
    degout = property(_wcs.WorldCoor_degout_get, _wcs.WorldCoor_degout_set, doc=r"""degout : int""")
    tabsys = property(_wcs.WorldCoor_tabsys_get, _wcs.WorldCoor_tabsys_set, doc=r"""tabsys : int""")
    rotmat = property(_wcs.WorldCoor_rotmat_get, _wcs.WorldCoor_rotmat_set, doc=r"""rotmat : int""")
    coorflip = property(_wcs.WorldCoor_coorflip_get, _wcs.WorldCoor_coorflip_set, doc=r"""coorflip : int""")
    offscl = property(_wcs.WorldCoor_offscl_get, _wcs.WorldCoor_offscl_set, doc=r"""offscl : int""")
    wcson = property(_wcs.WorldCoor_wcson_get, _wcs.WorldCoor_wcson_set, doc=r"""wcson : int""")
    naxis = property(_wcs.WorldCoor_naxis_get, _wcs.WorldCoor_naxis_set, doc=r"""naxis : int""")
    naxes = property(_wcs.WorldCoor_naxes_get, _wcs.WorldCoor_naxes_set, doc=r"""naxes : int""")
    wcsproj = property(_wcs.WorldCoor_wcsproj_get, _wcs.WorldCoor_wcsproj_set, doc=r"""wcsproj : int""")
    linmode = property(_wcs.WorldCoor_linmode_get, _wcs.WorldCoor_linmode_set, doc=r"""linmode : int""")
    detector = property(_wcs.WorldCoor_detector_get, _wcs.WorldCoor_detector_set, doc=r"""detector : int""")
    instrument = property(_wcs.WorldCoor_instrument_get, _wcs.WorldCoor_instrument_set, doc=r"""instrument : a(32).char""")
    ctype = property(_wcs.WorldCoor_ctype_get, _wcs.WorldCoor_ctype_set, doc=r"""ctype : a(9).a(9).char""")
    c1type = property(_wcs.WorldCoor_c1type_get, _wcs.WorldCoor_c1type_set, doc=r"""c1type : a(9).char""")
    c2type = property(_wcs.WorldCoor_c2type_get, _wcs.WorldCoor_c2type_set, doc=r"""c2type : a(9).char""")
    ptype = property(_wcs.WorldCoor_ptype_get, _wcs.WorldCoor_ptype_set, doc=r"""ptype : a(9).char""")
    units = property(_wcs.WorldCoor_units_get, _wcs.WorldCoor_units_set, doc=r"""units : a(9).a(32).char""")
    radecsys = property(_wcs.WorldCoor_radecsys_get, _wcs.WorldCoor_radecsys_set, doc=r"""radecsys : a(32).char""")
    radecout = property(_wcs.WorldCoor_radecout_get, _wcs.WorldCoor_radecout_set, doc=r"""radecout : a(32).char""")
    radecin = property(_wcs.WorldCoor_radecin_get, _wcs.WorldCoor_radecin_set, doc=r"""radecin : a(32).char""")
    eqin = property(_wcs.WorldCoor_eqin_get, _wcs.WorldCoor_eqin_set, doc=r"""eqin : double""")
    eqout = property(_wcs.WorldCoor_eqout_get, _wcs.WorldCoor_eqout_set, doc=r"""eqout : double""")
    sysin = property(_wcs.WorldCoor_sysin_get, _wcs.WorldCoor_sysin_set, doc=r"""sysin : int""")
    syswcs = property(_wcs.WorldCoor_syswcs_get, _wcs.WorldCoor_syswcs_set, doc=r"""syswcs : int""")
    sysout = property(_wcs.WorldCoor_sysout_get, _wcs.WorldCoor_sysout_set, doc=r"""sysout : int""")
    center = property(_wcs.WorldCoor_center_get, _wcs.WorldCoor_center_set, doc=r"""center : a(32).char""")
    wcsl = property(_wcs.WorldCoor_wcsl_get, _wcs.WorldCoor_wcsl_set, doc=r"""wcsl : struct wcsprm""")
    lin = property(_wcs.WorldCoor_lin_get, _wcs.WorldCoor_lin_set, doc=r"""lin : struct linprm""")
    cel = property(_wcs.WorldCoor_cel_get, _wcs.WorldCoor_cel_set, doc=r"""cel : struct celprm""")
    prj = property(_wcs.WorldCoor_prj_get, _wcs.WorldCoor_prj_set, doc=r"""prj : struct prjprm""")
    lngcor = property(_wcs.WorldCoor_lngcor_get, _wcs.WorldCoor_lngcor_set, doc=r"""lngcor : p.struct IRAFsurface""")
    latcor = property(_wcs.WorldCoor_latcor_get, _wcs.WorldCoor_latcor_set, doc=r"""latcor : p.struct IRAFsurface""")
    distcode = property(_wcs.WorldCoor_distcode_get, _wcs.WorldCoor_distcode_set, doc=r"""distcode : int""")
    distort = property(_wcs.WorldCoor_distort_get, _wcs.WorldCoor_distort_set, doc=r"""distort : struct Distort""")
    command_format = property(_wcs.WorldCoor_command_format_get, _wcs.WorldCoor_command_format_set, doc=r"""command_format : a(10).p.char""")
    ltm = property(_wcs.WorldCoor_ltm_get, _wcs.WorldCoor_ltm_set, doc=r"""ltm : a(4).double""")
    ltv = property(_wcs.WorldCoor_ltv_get, _wcs.WorldCoor_ltv_set, doc=r"""ltv : a(2).double""")
    idpix = property(_wcs.WorldCoor_idpix_get, _wcs.WorldCoor_idpix_set, doc=r"""idpix : a(2).int""")
    ndpix = property(_wcs.WorldCoor_ndpix_get, _wcs.WorldCoor_ndpix_set, doc=r"""ndpix : a(2).int""")
    wcs = property(_wcs.WorldCoor_wcs_get, _wcs.WorldCoor_wcs_set, doc=r"""wcs : p.struct WorldCoor""")
    wcsdep = property(_wcs.WorldCoor_wcsdep_get, _wcs.WorldCoor_wcsdep_set, doc=r"""wcsdep : p.struct WorldCoor""")
    wcsname = property(_wcs.WorldCoor_wcsname_get, _wcs.WorldCoor_wcsname_set, doc=r"""wcsname : p.char""")
    wcschar = property(_wcs.WorldCoor_wcschar_get, _wcs.WorldCoor_wcschar_set, doc=r"""wcschar : char""")
    logwcs = property(_wcs.WorldCoor_logwcs_get, _wcs.WorldCoor_logwcs_set, doc=r"""logwcs : int""")

    def __init__(self):
        _wcs.WorldCoor_swiginit(self, _wcs.new_WorldCoor())
    __swig_destroy__ = _wcs.delete_WorldCoor

# Register WorldCoor in _wcs:
_wcs.WorldCoor_swigregister(WCSPRM)

