name: Build for Windows

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  
jobs:
    build-win:
      runs-on: windows-2019
      strategy:
        fail-fast: false
  
      steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          
      - name: Install Python dependencies
        run: |
          pip install pyinstaller
          pip install .

      - name: Build Image Marker
        run: |
          cd pyinstaller
          pyinstaller win.spec
          ls
      
      - name: Zip
        run: |
          cd D:\a\imgmarker\imgmarker\pyinstaller\dist
          Compress-Archive -Path 'Image Marker' -DestinationPath 'imgmarker.zip'
          ls

      - name: Get latest release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      #- name: Upload release build
      #  id: upload-release-asset 
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
      #    asset_path: D:\a\imgmarker\imgmarker\pyinstaller\dist\imgmarker.zip
      #    asset_name: imgmarker-${{ steps.latest_release_info.outputs.tag_name }}-win.zip
      #    asset_content_type: application/zip

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: Image Marker (Windows)
            path: D:\a\imgmarker\imgmarker\pyinstaller\dist
