name: Build for Mac (M1+)

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
    build-mac:
      runs-on: macos-14
      strategy:
        fail-fast: false
  
      steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install Python dependencies
        run: |
          pip install pyinstaller
          pip install .

      - name: Build Image Marker
        run: |
          cd pyinstaller
          pyinstaller mac.spec
          ls

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: imgmarker-mac
            path: /Users/runner/work/imgmarker/imgmarker/pyinstaller/dist