name: Build for Windows

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
    build-win:
      runs-on: windows-2019
      strategy:
        fail-fast: false
  
      steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          
      - name: Install Python dependencies
        run: |
          pip install pyinstaller
          pip install .

      - name: Build Image Marker
        run: |
          cd pyinstaller
          pyinstaller win.spec
          ls
      
      - name: Zip
        run: |
          cd D:\a\imgmarker\imgmarker\pyinstaller\dist
          zip -r 'Image Marker (Windows).zip' 'Image Marker'

      - name: Release the new binaries
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          prerelease: true
          files: |
            Image Marker (Windows).zip
          clear_attachments: true
          skip_tag_creation: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: Image Marker (Windows)
            path: D:\a\imgmarker\imgmarker\pyinstaller\dist
