name: Build
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Reference (tag, branch, etc)
        required: true

  release:
    types: [published]

permissions:
  id-token: write
  contents: write
  
jobs:
  setup:  
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.set-ref.outputs.ref }}

    steps:
      - name: Set ref 
        id: set-ref
        if: ${{ github.event_name == 'workflow_dispatch'}}
        run: |
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            echo "ref=${{inputs.ref}}" >> $GITHUB_OUTPUT
          else
            echo "ref=${{github.ref_name}}" >> $GITHUB_OUTPUT
          fi      

  build:
    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            spec: win
            arch: x64
          - os: macos-14
            spec: mac
            arch: arm64
          - os: macos-13
            spec: mac
            arch: x64

    runs-on: ${{matrix.os}}  

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{needs.setup.outputs.ref}}
    
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        
    - name: Install Python dependencies
      run: |
        pip install pyinstaller
        pip install .

    - name: Build Image Marker
      run: |

        cd ${{github.workspace}}/pyinstaller
        pyinstaller  ${{matrix.spec}}.spec
  
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: imgmarker-${{needs.setup.outputs.ref}}-${{matrix.spec}}-${{matrix.arch}}
        path: ${{github.workspace}}/pyinstaller/dist 
  
  upload:
    needs: [setup,build]
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - spec: win
            arch: x64
          - spec: mac
            arch: arm64
          - spec: mac
            arch: x64

    runs-on: ubuntu-latest
    
    if: startsWith(needs.setup.outputs.ref, 'v')
    steps:
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: imgmarker-${{needs.setup.outputs.ref}}-${{matrix.spec}}-${{matrix.arch}}
          path: artifact
          merge-multiple: true
      - run: |
          ls artifact
          echo ${{ steps.download-artifact.outputs.download-path }}

      - name: Upload artifact to release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.download-artifact.outputs.download-path }}
          asset_name: imgmarker-${{needs.setup.outputs.ref}}-${{matrix.spec}}-${{matrix.arch}}.zip
          asset_content_type: application/zip


