name: Build for Windows

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
    build-win:
      runs-on: windows-2019
      strategy:
        fail-fast: false
  
      steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          
      - name: Install Python dependencies
        run: |
          pip install pyinstaller
          pip install .

      - name: Build Image Marker
        run: |
          cd pyinstaller
          pyinstaller win.spec
          ls

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: imgmarker-win
            path: D:\a\imgmarker\imgmarker\pyinstaller\dist
